extends RefCounted
class_name PresetLibrary

# Presets are intentionally explicit. Each note calls out why the scenario is interesting,
# and whether it changes the physical assumptions from the isolated elastic baseline.

static func sandbox_defaults() -> Dictionary:
	return {
		"preset_id": "sandbox",
		"label": "Demonstracija",
		"atom_count": 25,
		"t_left": 1.8,
		"t_right": 0.45,
		"wall_coupling": 0.0,
		"radius": 0.21,
		"gate_height": 2.25,
		"bin_x": 4,
		"bin_y": 4,
		"speed_bins": 6,
		"physics_substeps": 3,
		"ai_lookahead_steps": 5,
		"presentation_gate_seed": true,
		"bimodal_demo_init": true,
		"slow_speed": 2.0,
		"fast_speed": 9.0,
		"left_fast_fraction": 0.25,
		"right_fast_fraction": 0.75,
		"perfect_demon_ai": false,
		"include_bookkeeping": false,
		"theory_note": "Demonstracioni režim: svaka komora počinje kao mešavina sporih i brzih sa podesivim udelom brzih čestica. Ovo je namerno prezentaciona inicijalizacija, a ne teorijska temperaturna inicijalizacija."
	}

static func presets() -> Array[Dictionary]:
	return [
		{
			"preset_id": "szilard_low_n",
			"label": "Mali broj čestica",
			"atom_count": 4,
			"t_left": 1.0,
			"t_right": 1.0,
			"wall_coupling": 0.0,
			"radius": 0.31,
			"gate_height": 3.05,
			"bin_x": 2,
			"bin_y": 3,
			"speed_bins": 4,
			"physics_substeps": 3,
			"ai_lookahead_steps": 5,
			"presentation_gate_seed": false,
			"bimodal_demo_init": true,
			"slow_speed": 2.0,
			"fast_speed": 9.0,
			"left_fast_fraction": 0.5,
			"right_fast_fraction": 0.5,
			"perfect_demon_ai": false,
			"include_bookkeeping": false,
			"theory_note": "Vrlo mali broj čestica sa istim kontrolama za udeo brzih kao u demonstraciji. Interakcija ostaje ista, a priča o informaciji i selekciji je lakša za objasniti."
		},
		{
			"preset_id": "low_density_sorting",
			"label": "Ređi sudari",
			"atom_count": 28,
			"t_left": 1.25,
			"t_right": 0.85,
			"wall_coupling": 0.0,
			"radius": 0.17,
			"gate_height": 2.45,
			"bin_x": 4,
			"bin_y": 4,
			"speed_bins": 6,
			"physics_substeps": 3,
			"ai_lookahead_steps": 5,
			"presentation_gate_seed": false,
			"bimodal_demo_init": true,
			"slow_speed": 2.0,
			"fast_speed": 9.0,
			"left_fast_fraction": 0.5,
			"right_fast_fraction": 0.5,
			"perfect_demon_ai": false,
			"include_bookkeeping": false,
			"theory_note": "Mala gustina znači manje sudara parova, pa isti klizači za levi i desni udeo brzih daju jasniju i čitljiviju demonstraciju sortiranja."
		},
		{
			"preset_id": "dense_collisional",
			"label": "Gusti gas",
			"atom_count": 80,
			"t_left": 1.15,
			"t_right": 0.95,
			"wall_coupling": 0.0,
			"radius": 0.23,
			"gate_height": 2.05,
			"bin_x": 5,
			"bin_y": 4,
			"speed_bins": 6,
			"physics_substeps": 4,
			"ai_lookahead_steps": 5,
			"presentation_gate_seed": false,
			"bimodal_demo_init": true,
			"slow_speed": 2.0,
			"fast_speed": 9.0,
			"left_fast_fraction": 0.5,
			"right_fast_fraction": 0.5,
			"perfect_demon_ai": false,
			"include_bookkeeping": false,
			"theory_note": "Česti sudari brzo preraspodeljuju impuls. Iste kontrole za udeo brzih ovde rade u gušćem režimu sa jačim mešanjem."
		},
		{
			"preset_id": "bath_assisted",
			"label": "Sprega sa zidom",
			"atom_count": 48,
			"t_left": 1.2,
			"t_right": 0.8,
			"wall_coupling": 0.18,
			"radius": 0.21,
			"gate_height": 2.25,
			"bin_x": 4,
			"bin_y": 4,
			"speed_bins": 6,
			"physics_substeps": 3,
			"ai_lookahead_steps": 5,
			"presentation_gate_seed": false,
			"bimodal_demo_init": true,
			"slow_speed": 2.0,
			"fast_speed": 9.0,
			"left_fast_fraction": 0.5,
			"right_fast_fraction": 0.5,
			"perfect_demon_ai": false,
			"include_bookkeeping": false,
			"theory_note": "Iste kontrole za udeo brzih su ovde uparene sa neizolovanim upijanjem na zidu. Ovaj preset je i dalje eksplicitno aproksimacija sa kupatilom, a ne čista Hamiltonova evolucija."
		}
	]
